### ISSUE TITLE
Svelte 3

### ISSUE THREAD

**Issue by enricribas** [d-lowl/chrome-extension-svelte-boilerplate#1]
I'm trying to update to Svelte but having some issues. Any plans to update?
Thanks for creating this.

**Comment by d-lowl** [comment]
I had no plans essentially, but I can look into it next week (when I am less busy). Any specific issues with Svelte 3 you want me to look into?

**Comment by enricribas** [comment]
That would be awesome. I managed to get `npm run build` to work but can't seem to get the hotloading to work with chrome extension.

**Comment by d-lowl** [comment]
Upgraded to Svelte 3 + some other packages for compatibility. Now it should work just fine (tested it in Brave)

**Comment by d-lowl** [comment]
@enricribas pinging the OP, in case there was no notification

**Comment by enricribas** [comment]
Not sure if I'm doing something wrong or it's the webpack setup but I narrowed down the issue that I was having and am still seeing it with your changes. 
When I use a nested component, and `npm run build` and install the extension locally, it works.
However using `npm run start`, I get a blank popup in the extension when I load from the build directory.

Any ideas?  Thanks.

**Comment by enricribas** [comment]
@d-lowl Not going to re-open but if you have any insights into the above, I'd appreciate it.

**Comment by NasirKhalid24** [comment]
Currently facing the same issue as mentioned by @enricribas, if the little white box is right clicked you can open up the console for it through 'inspect element'. The error that it gives is attached

![Screen Shot 2019-07-18 at 2 15 20 PM](https://user-images.githubusercontent.com/29706203/61449725-98649e00-a966-11e9-9704-25bb295d9cab.png)
