### ISSUE TITLE
Svelte component import not working

### ISSUE THREAD

**Issue by NasirKhalid24** [d-lowl/chrome-extension-svelte-boilerplate#2]
This problem was first referenced in #1 . Currently if a component is imported in to a svelte file there is no popup in development mode. Only when a complete production build is created does it work. For example, currently in my Popup.svelte I have added the following line in the script tag

```javascript
import Bar from './Bar.svelte';
```

and in Bar.svelte I have only the following line

```html
<h2>Hello Again</h2>
```

When I run the development server I get the following popup.
![Screen Shot 2019-07-18 at 2 20 18 PM](https://user-images.githubusercontent.com/29706203/61450012-32c4e180-a967-11e9-84ec-94ff4bd87e85.png)

When the console for the popup is opened it shows the following errors

![Screen Shot 2019-07-18 at 2 15 20 PM](https://user-images.githubusercontent.com/29706203/61450036-407a6700-a967-11e9-8a95-e6094aa0c0f3.png)

However if instead you run 'npm run build' the extension then displays as required

![Screen Shot 2019-07-18 at 2 22 01 PM](https://user-images.githubusercontent.com/29706203/61450121-73245f80-a967-11e9-86a9-11924affb326.png)

**Comment by NasirKhalid24** [comment]
Fixed now #3

**Comment by d-lowl** [comment]
Thanks for the help @NasirKhalid24, merged.
